title: The O'Shaughnessy Research Group
email: richard.oshaughnessy@rit.edu
description: Advancing our understanding of the Universe through Gravitational Wave Astronomy and Multimessenger Astrophysics.
baseurl: "/outward-facing-web"
url: "https://oshaughnessy-junior.github.io"
theme: minima
