title: Richard O'Shaughnessy
email: richard.oshaughnessy@rit.edu
description: Assistant Professor of Mathematical Sciences at RIT, specializing in Gravitational Wave Astronomy.
baseurl: "/outward-facing-web"
url: "https://oshaughnessy-junior.github.io"
theme: minima
